sudo: required
solution: TrisvagoHotels.sln
language: csharp
mono: none
dotnet: 3.0.100
addons:
  sonarcloud:
    organization: "zpecter-github"
install:
  - sudo apt-get install -qq dotnet-sdk-3.0
  - dotnet restore
script:
  - dotnet build
