sudo: required
solution: TrisvagoHotels.sln
language: csharp
mono: none
dotnet: 3.1.101
git:
  depth: false
addons:
  sonarcloud:
    organization: "zpecter-github"
    
before_install:
  - bash ./tools/travis-ci-install-sonar.sh

install:
  - sudo apt-get install -qq dotnet-sdk-3.1.101
  - dotnet restore

script:
  - dotnet build
  - bash ./tools/travis-ci-build.sh
