name: .NET Core

on:
  push:
     branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: 8.x
  SCANNER_VERSION: 10.3.0.120579

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build_config: Release
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dependencies
      run:  dotnet restore
    
    - name: Build with dotnet
      run: dotnet build --configuration $build_config --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  
    - name: Publish site
      working-directory: ./src/TrisvagoHotels.Host
      run: dotnet publish -c $build_config --no-restore -o ../Publish
        
    - name: Upload web site
      uses: actions/upload-artifact@v4
      with:
        name: web_site
        path: ./src/Publish

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        #scannerVersion: ${{ env.SCANNER_VERSION }}
        args: >
          -Dsonar.organization='${{ secrets.SONAR_ORGANIZATION }}'
          -Dsonar.projectKey='${{ secrets.SONAR_PROJECT_KEY }}'

  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download site
        uses: actions/download-artifact@v4
        with:
          name: web_site
          path: web_site
