name: PR Verify

on:
  pull_request:
    branches: ["main"]

env:
  DOTNET_VERSION: 8.x

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: .NET restore
        run: dotnet restore --locked-mode

      - name: .NET build
        run: dotnet build --configuration Release --no-restore

      - name: .NET test
        run: dotnet test --configuration Release --no-build
